### ISSUE TITLE
Error: No possible parsings

### ISSUE THREAD

**Issue by scwood** [Picolab/node-krl-compiler#2]
I get a syntax error with the following:

```
  rule process_trip_new {
    select when car new_trip
    fired {
      raise explicit event "trip_processed"
        with mileage = event:attr("mileage")
          and time = time:now();
    }
  }
```
```
Error: No possible parsings
:19:15

          and time = time:now();
              ^
```

If I remove the 'and' statement it works. 

```
  rule process_trip_new {
    select when car new_trip
    fired {
      raise explicit event "trip_processed"
        with mileage = event:attr("mileage")
    }
  }
```

According to the documentation this is the correct syntax. What am I doing wrong?

https://picolabs.atlassian.net/wiki/spaces/docs/pages/1189896/Raising+Explicit+Events+in+the+Postlude

**Comment by farskipper** [comment]
The new parser doesn't use "and" so just change it like this
```
      raise explicit event "trip_processed"
        with mileage = event:attr("mileage")
             time = time:now();
```
Sorry the docs were telling you something different.

@b1conrad I guess we'll need to update the docs or decide to allow "and"s in those lists
